version: "3.9"
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - web
    links:
      - web
    volumes:
      - ./nginx:/etc/nginx/conf.d
  web:
    build: ./web
    restart: always
    depends_on:
      - redis
    links:
      - redis
    command: gunicorn --bind 0.0.0.0:5000 main:app
    ports:
      - 5000:5000
    volumes:
      - ./web/:/app/
  redis:
    image: "redis:alpine"
    expose:
      - "6379"